INSERT INTO BANK_ACCOUNT  VALUES (10, 0); 
INSERT INTO BANK_ACCOUNT  VALUES (20, 0); 
INSERT INTO BANK_ACCOUNT  VALUES (30, 0);
INSERT INTO BANK_ACCOUNT  VALUES (40, 0);
INSERT INTO BANK_ACCOUNT  VALUES (50, 0);